/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as SSlugRouteImport } from './routes/s.$slug'
import { Route as ApiPublicPushStreamRouteImport } from './routes/api/public/push-stream'
import { Route as ApiPublicChatRouteImport } from './routes/api/public/chat'
import { Route as AuthenticatedPProjectIdRouteImport } from './routes/_authenticated/p.$projectId'
import { Route as AuthenticatedAccountBillingRouteImport } from './routes/_authenticated/account.billing'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe.webhook'
import { Route as ApiPublicGithubCallbackRouteImport } from './routes/api/public/github.callback'

const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const SSlugRoute = SSlugRouteImport.update({
  id: '/s/$slug',
  path: '/s/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPushStreamRoute = ApiPublicPushStreamRouteImport.update({
  id: '/api/public/push-stream',
  path: '/api/public/push-stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicChatRoute = ApiPublicChatRouteImport.update({
  id: '/api/public/chat',
  path: '/api/public/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPProjectIdRoute = AuthenticatedPProjectIdRouteImport.update({
  id: '/p/$projectId',
  path: '/p/$projectId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountBillingRoute =
  AuthenticatedAccountBillingRouteImport.update({
    id: '/account/billing',
    path: '/account/billing',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe/webhook',
  path: '/api/public/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGithubCallbackRoute = ApiPublicGithubCallbackRouteImport.update({
  id: '/api/public/github/callback',
  path: '/api/public/github/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/templates': typeof TemplatesRoute
  '/s/$slug': typeof SSlugRoute
  '/account/billing': typeof AuthenticatedAccountBillingRoute
  '/p/$projectId': typeof AuthenticatedPProjectIdRoute
  '/api/public/chat': typeof ApiPublicChatRoute
  '/api/public/push-stream': typeof ApiPublicPushStreamRoute
  '/api/public/github/callback': typeof ApiPublicGithubCallbackRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/templates': typeof TemplatesRoute
  '/s/$slug': typeof SSlugRoute
  '/': typeof AuthenticatedIndexRoute
  '/account/billing': typeof AuthenticatedAccountBillingRoute
  '/p/$projectId': typeof AuthenticatedPProjectIdRoute
  '/api/public/chat': typeof ApiPublicChatRoute
  '/api/public/push-stream': typeof ApiPublicPushStreamRoute
  '/api/public/github/callback': typeof ApiPublicGithubCallbackRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/templates': typeof TemplatesRoute
  '/s/$slug': typeof SSlugRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/account/billing': typeof AuthenticatedAccountBillingRoute
  '/_authenticated/p/$projectId': typeof AuthenticatedPProjectIdRoute
  '/api/public/chat': typeof ApiPublicChatRoute
  '/api/public/push-stream': typeof ApiPublicPushStreamRoute
  '/api/public/github/callback': typeof ApiPublicGithubCallbackRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/templates'
    | '/s/$slug'
    | '/account/billing'
    | '/p/$projectId'
    | '/api/public/chat'
    | '/api/public/push-stream'
    | '/api/public/github/callback'
    | '/api/public/stripe/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/templates'
    | '/s/$slug'
    | '/'
    | '/account/billing'
    | '/p/$projectId'
    | '/api/public/chat'
    | '/api/public/push-stream'
    | '/api/public/github/callback'
    | '/api/public/stripe/webhook'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/templates'
    | '/s/$slug'
    | '/_authenticated/'
    | '/_authenticated/account/billing'
    | '/_authenticated/p/$projectId'
    | '/api/public/chat'
    | '/api/public/push-stream'
    | '/api/public/github/callback'
    | '/api/public/stripe/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  TemplatesRoute: typeof TemplatesRoute
  SSlugRoute: typeof SSlugRoute
  ApiPublicChatRoute: typeof ApiPublicChatRoute
  ApiPublicPushStreamRoute: typeof ApiPublicPushStreamRoute
  ApiPublicGithubCallbackRoute: typeof ApiPublicGithubCallbackRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/s/$slug': {
      id: '/s/$slug'
      path: '/s/$slug'
      fullPath: '/s/$slug'
      preLoaderRoute: typeof SSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/push-stream': {
      id: '/api/public/push-stream'
      path: '/api/public/push-stream'
      fullPath: '/api/public/push-stream'
      preLoaderRoute: typeof ApiPublicPushStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/chat': {
      id: '/api/public/chat'
      path: '/api/public/chat'
      fullPath: '/api/public/chat'
      preLoaderRoute: typeof ApiPublicChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/p/$projectId': {
      id: '/_authenticated/p/$projectId'
      path: '/p/$projectId'
      fullPath: '/p/$projectId'
      preLoaderRoute: typeof AuthenticatedPProjectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account/billing': {
      id: '/_authenticated/account/billing'
      path: '/account/billing'
      fullPath: '/account/billing'
      preLoaderRoute: typeof AuthenticatedAccountBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/stripe/webhook': {
      id: '/api/public/stripe/webhook'
      path: '/api/public/stripe/webhook'
      fullPath: '/api/public/stripe/webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/github/callback': {
      id: '/api/public/github/callback'
      path: '/api/public/github/callback'
      fullPath: '/api/public/github/callback'
      preLoaderRoute: typeof ApiPublicGithubCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAccountBillingRoute: typeof AuthenticatedAccountBillingRoute
  AuthenticatedPProjectIdRoute: typeof AuthenticatedPProjectIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAccountBillingRoute: AuthenticatedAccountBillingRoute,
  AuthenticatedPProjectIdRoute: AuthenticatedPProjectIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  TemplatesRoute: TemplatesRoute,
  SSlugRoute: SSlugRoute,
  ApiPublicChatRoute: ApiPublicChatRoute,
  ApiPublicPushStreamRoute: ApiPublicPushStreamRoute,
  ApiPublicGithubCallbackRoute: ApiPublicGithubCallbackRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
